openapi: 3.0.3
info:
  title: Bank System Project API
  version: 1.0.0
  description: Bank System Project API
paths:
  /accounts/:
    get:
      operationId: accounts_list
      tags:
      - accounts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
          description: ''
    post:
      operationId: accounts_create
      tags:
      - accounts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Account'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
          description: ''
  /accounts/{id}/:
    get:
      operationId: accounts_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - accounts
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetail'
          description: ''
  /banks/:
    get:
      operationId: banks_list
      tags:
      - banks
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bank'
          description: ''
    post:
      operationId: banks_create
      tags:
      - banks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bank'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bank'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
          description: ''
  /banks/{id}/:
    get:
      operationId: banks_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - banks
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
          description: ''
    put:
      operationId: banks_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - banks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bank'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bank'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bank'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
          description: ''
    patch:
      operationId: banks_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - banks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBank'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBank'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBank'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bank'
          description: ''
    delete:
      operationId: banks_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - banks
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /branchs/:
    get:
      operationId: branchs_list
      tags:
      - branchs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Branch'
          description: ''
    post:
      operationId: branchs_create
      tags:
      - branchs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Branch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Branch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Branch'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ''
  /branchs/{id}/:
    get:
      operationId: branchs_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - branchs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ''
    put:
      operationId: branchs_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - branchs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Branch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Branch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Branch'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ''
    patch:
      operationId: branchs_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - branchs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBranch'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBranch'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBranch'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
          description: ''
    delete:
      operationId: branchs_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - branchs
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /create_account/:
    post:
      operationId: create_account_create
      tags:
      - create_account
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /deposite/:
    get:
      operationId: deposite_list
      tags:
      - deposite
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Deposite'
          description: ''
    post:
      operationId: deposite_create
      tags:
      - deposite
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deposite'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Deposite'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Deposite'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deposite'
          description: ''
  /withdraw/:
    get:
      operationId: withdraw_list
      tags:
      - withdraw
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Withdraw'
          description: ''
    post:
      operationId: withdraw_create
      tags:
      - withdraw
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Withdraw'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Withdraw'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Withdraw'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Withdraw'
          description: ''
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        clients:
          $ref: '#/components/schemas/Client'
        bank:
          $ref: '#/components/schemas/Bank'
        account_type:
          type: string
          maxLength: 100
        open_date:
          type: string
          maxLength: 100
      required:
      - account_type
      - bank
      - clients
      - id
      - open_date
    AccountDetail:
      type: object
      properties:
        clients:
          $ref: '#/components/schemas/Client'
        bank:
          $ref: '#/components/schemas/Bank'
        balance:
          type: string
          format: decimal
          pattern: ^-?\d{0,3}(?:\.\d{0,2})?$
        open_date:
          type: string
          maxLength: 100
      required:
      - balance
      - bank
      - clients
      - open_date
    Bank:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        branch:
          $ref: '#/components/schemas/Branch'
        name:
          type: string
          maxLength: 255
      required:
      - branch
      - id
      - name
    Branch:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        address:
          type: string
          maxLength: 255
        branch_code:
          type: string
          maxLength: 255
      required:
      - address
      - branch_code
      - id
      - name
    Client:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        address:
          type: string
          maxLength: 255
      required:
      - address
      - id
      - name
    Deposite:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        amount:
          type: number
          format: double
        account:
          type: integer
      required:
      - account
      - amount
      - id
    PatchedBank:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        branch:
          $ref: '#/components/schemas/Branch'
        name:
          type: string
          maxLength: 255
    PatchedBranch:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        address:
          type: string
          maxLength: 255
        branch_code:
          type: string
          maxLength: 255
    Withdraw:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        amount:
          type: number
          format: double
        account:
          type: integer
      required:
      - account
      - amount
      - id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
